[general]
destination = "$HOME/.config/hypr/config.d/dynamic-monitors.conf"

[profiles.laptop]
config_file = "hyprconfigs/laptop.go.tmpl"
config_file_type = "template"

[[profiles.laptop.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "laptop"

[profiles.waw_1]
config_file = "hyprconfigs/waw_1.go.tmpl"
config_file_type = "template"

[[profiles.waw_1.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "laptop"

[[profiles.waw_1.conditions.required_monitors]]
description = "LG Electronics LG SDQHD 301NTBKDU037"
monitor_tag = "external"

[profiles.waw_2]
config_file = "hyprconfigs/waw_2.go.tmpl"
config_file_type = "template"

[[profiles.waw_2.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "laptop"

[[profiles.waw_2.conditions.required_monitors]]
description = "Technical Concepts Ltd Beyond TV 0x00010000"
monitor_tag = "external"

[profiles.ldn_1]
config_file = "hyprconfigs/ldn_1.go.tmpl"
config_file_type = "template"

[[profiles.ldn_1.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "laptop"

[[profiles.ldn_1.conditions.required_monitors]]
description = "LG Electronics LG ULTRAFINE 411NTAB69680"

[profiles.ldn_2]
config_file = "hyprconfigs/ldn_2.go.tmpl"
config_file_type = "template"

[[profiles.ldn_2.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "laptop"

[[profiles.ldn_2.conditions.required_monitors]]
description = "LG Electronics LG TV 0x01010101"
monitor_tag = "external"

[fallback_profile]
config_file = "hyprconfigs/fallback.conf"
config_file_type = "static"

[profiles.waw_3]
config_file = "/home/fmikina/.config/hyprdynamicmonitors/hyprconfigs/waw_3.go.tmpl"
config_file_type = "template"
[profiles.waw_3.conditions]

[[profiles.waw_3.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "monitor0"

[[profiles.waw_3.conditions.required_monitors]]
description = "Sony SONY TV  *30 0x01010101"
monitor_tag = "monitor1"


[profiles.ldn_3]
config_file = "/home/fmikina/.config/hyprdynamicmonitors/hyprconfigs/ldn_3.go.tmpl"
config_file_type = "template"
[profiles.ldn_3.conditions]

[[profiles.ldn_3.conditions.required_monitors]]
description = "BOE NE135A1M-NY1"
monitor_tag = "laptop"

[[profiles.ldn_3.conditions.required_monitors]]
description = "Dell Inc. DELL U2725QE 2BRJ734"
monitor_tag = "external"
